version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-http://localhost:5173}
    volumes:
      - ./cha_panelas.db:/app/cha_panelas.db
    restart: unless-stopped
  frontend-dev:
    image: node:20-alpine
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - VITE_API_URL=http://localhost:5000/api

# Uso:
# Desenvolvimento:
#   export ALLOWED_ORIGIN=http://localhost:5173
#   docker compose up --build
# Produção (GitHub Pages):
#   export ALLOWED_ORIGIN=https://barcelosvs.github.io/cha-de-panelas
#   docker compose up -d
